language: python
python:
- 3.8.2
before_install:
- pip install poetry
install:
- pip install coveralls
- poetry install
script:
- poetry run pytest
after_success:
- coverage
- coveralls
notifications:
  slack:
    secure: mFM+W9U3FakO9MRQgQmT6qvm0LfuebpHgNNwRMallwzD8XYQIhZs4ThZEAw8lSJdYHq+3lx318wvXesyF75zOiON73597fRtGyvr+Oeii0hCzz8Y9bW92xCDyYLZYZA9t+ZUT4ZfS9fWFjMZ0f21/Cy+KFVJqq8Lf92FDgw/wjtHcEMVi9AQU6neGXihECM5kwwdE0JStc9EP4kpaiWnAexOmy8vn7FOpDZaUR9rY78iUlCFNEGzVPdLre0Uw2xRx8MDoLBc8XoH4yYj/JMJf3aFwe2NKpHbHZk8EWvvmdCmPeC1LOI28w3jmjR9Bh0v20XP/Z5ho2WuYGF2gPV0FyRYOD7yS0ya7RM4XcXNExwkLe+lGiaUAerqxF/MbJSt1XiX3Yo7c65hQ3wsOUuaLYtvA+X97fOfU4hYr+GZ5kJJ0va1L3n/Tdh0nrxMGjJm5mlb1zBFk6YP0nNzVGDKaJmBIF9VkDmWb/h/Bl38uKLUEqVJXkT9speOJFmbC/6R281DaYeNEqhiCLvEC4rRXWG9DpJ9KgsaHpq7hhzNQkZRFj/iMqTq6uLStnJvnLVps6oD45K96EJZ+CrEfgfE1uRCKl8yd5ryurgcZkpBA9ntFZ4mKiFr73s3BZ4+UNnyYAtW2FGeEp/u319wk33OeMcs3pcZ8nPvKLuJ3XngqbU=
